version: 2

updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      bun-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      docker-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 3
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      docker-compose-minor-patch:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
