export { default as ProfileForm } from './ProfileForm.vue'
export { default as PasswordForm } from './PasswordForm.vue'
export { default as ProfilePictureForm } from './ProfilePictureForm.vue'
export { default as DangerZone } from './DangerZone.vue'
export { default as SessionsManager } from './SessionsManager.vue'
